#### breast_cancer.data Column Details


 Attribute Information: (class attribute has been moved to last column)<br>
<pre>
     Attribute                     Domain
   -- -----------------------------------------
1. Sample code number            id number
2. Clump Thickness               1 - 10
3. Uniformity of Cell Size       1 - 10
4. Uniformity of Cell Shape      1 - 10
5. Marginal Adhesion             1 - 10
6. Single Epithelial Cell Size   1 - 10
7. Bare Nuclei                   1 - 10
8. Bland Chromatin               1 - 10
9. Normal Nucleoli               1 - 10
10. Mitoses                      1 - 10
11. Class:                       (2 for benign, 4 for malignant)
</pre>

#### Classification Exercise

1) Read the dataset 'breast_cancer.data'<br>
2) Remove/handle the null values.<br>
3) Rename the column names appropritely as per the attribute info mentioned above<br>
4) Based on the general understanding of the dataset, select independent features and dependent feature<br>
5) Split the dataset into training and testing dataset with test_size 25%<br>
6) Apply Decision Tree Classification and predict the class for the test data.<br>
7) Find the confusion matrix, accuracy_score and generate classification_report.<br>
8) Apply Radom Forest Classification and predict the class for the test data.<br>
9) Find the confusion matrix, accuracy_score and generate classification_report.<br>


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('D:\PYTHON ALL/breast_cancer.data')

In [3]:
df.head(30)

1000025   5   1  1.1  1.2  2 1.3  3  1.4  1.5  2.1
0   1002945   5   4    4    5  7  10  3    2    1    2
1   1015425   3   1    1    1  2   2  3    1    1    2
2   1016277   6   8    8    1  3   4  3    7    1    2
3   1017023   4   1    1    3  2   1  3    1    1    2
4   1017122   8  10   10    8  7  10  9    7    1    4
5   1018099   1   1    1    1  2  10  3    1    1    2
6   1018561   2   1    2    1  2   1  3    1    1    2
7   1033078   2   1    1    1  2   1  1    1    5    2
8   1033078   4   2    1    1  2   1  2    1    1    2
9   1035283   1   1    1    1  1   1  3    1    1    2
10  1036172   2   1    1    1  2   1  2    1    1    2
11  1041801   5   3    3    3  2   3  4    4    1    4
12  1043999   1   1    1    1  2   3  3    1    1    2
13  1044572   8   7    5   10  7   9  5    5    4    4
14  1047630   7   4    6    4  6   1  4    3    1    4
15  1048672   4   1    1    1  2   1  2    1    1    2
16  1049815   4   1    1    1  2   1  3    1    1    2
17  1050670  10   7    7    6  4  10  4    1    2    4
18  1050718   6   1    1    1  2   1  3    1    1    2
19  1054590   7   3    2   10  5  10  5    4    4    4
20  1054593  10   5    5    3  6   7  7   10    1    4
21  1056784   3   1    1    1  2   1  2    1    1    2
22  1057013   8   4    5    1  2   ?  7    3    1    4
23  1059552   1   1    1    1  2   1  3    1    1    2
24  1065726   5   2    3    4  2   7  3    6    1    4
25  1066373   3   2    1    1  1   1  2    1    1    2
26  1066979   5   1    1    1  2   1  2    1    1    2
27  1067444   2   1    1    1  2   1  2    1    1    2
28  1070935   1   1    3    1  2   1  1    1    1    2
29  1070935   3   1    1    1  1   1  2    1    1    2

In [4]:
df.isnull().sum()

1000025    0
5          0
1          0
1.1        0
1.2        0
2          0
1.3        0
3          0
1.4        0
1.5        0
2.1        0
dtype: int64

In [5]:
df.rename(columns=({ '1000025': 'Sample code number', '5': 'Clump Thickness','1': 'Uniformity of Cell Size', '1.1': 'Uniformity of Cell Shape','1.2': 'Marginal Adhesion', 
                    '2': 'Single Epithelial Cell Size','1.3': 'Bare Nuclei', '3': 'Bland Chromatin', 
                    '1.4': 'Normal Nucleoli','1.5': 'Mitoses','2.1': 'Class:'}),inplace=True)
df

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1002945                5                        4   
1               1015425                3                        1   
2               1016277                6                        8   
3               1017023                4                        1   
4               1017122                8                       10   
..                  ...              ...                      ...   
693              776715                3                        1   
694              841769                2                        1   
695              888820                5                       10   
696              897471                4                        8   
697              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           4                  5                            7   
1                           1                  1                            2   
2                           8                  1                            3   
3                           1                  3                            2   
4                          10                  8                            7   
..                        ...                ...                          ...   
693                         1                  1                            3   
694                         1                  1                            2   
695                        10                  3                            7   
696                         6                  4                            3   
697                         8                  5                            4   

    Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class:  
0            10                3                2        1       2  
1             2                3                1        1       2  
2             4                3                7        1       2  
3             1                3                1        1       2  
4            10                9                7        1       4  
..          ...              ...              ...      ...     ...  
693           2                1                1        1       2  
694           1                1                1        1       2  
695           3                8               10        2       4  
696           4               10                6        1       4  
697           5               10                4        1       4  

[698 rows x 11 columns]

### Based on the general understanding of the dataset, select independent features and dependent feature

In [17]:
df.describe()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
count        6.980000e+02       698.000000               698.000000   
mean         1.071807e+06         4.416905                 3.137536   
std          6.175323e+05         2.817673                 3.052575   
min          6.163400e+04         1.000000                 1.000000   
25%          8.702582e+05         2.000000                 1.000000   
50%          1.171710e+06         4.000000                 1.000000   
75%          1.238354e+06         6.000000                 5.000000   
max          1.345435e+07        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                698.000000         698.000000   
mean                   3.210602           2.809456   
std                    2.972867           2.856606   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.000000           1.000000   
75%                    5.000000           4.000000   
max                   10.000000          10.000000   

       Single Epithelial Cell Size  Bland Chromatin  Normal Nucleoli  \
count                   698.000000       698.000000       698.000000   
mean                      3.217765         3.438395         2.869628   
std                       2.215408         2.440056         3.055004   
min                       1.000000         1.000000         1.000000   
25%                       2.000000         2.000000         1.000000   
50%                       2.000000         3.000000         1.000000   
75%                       4.000000         5.000000         4.000000   
max                      10.000000        10.000000        10.000000   

          Mitoses      Class:  
count  698.000000  698.000000  
mean     1.590258    2.690544  
std      1.716162    0.951596  
min      1.000000    2.000000  
25%      1.000000    2.000000  
50%      1.000000    2.000000  
75%      1.000000    4.000000  
max     10.000000    4.000000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Sample code number           698 non-null    int64 
 1   Clump Thickness              698 non-null    int64 
 2   Uniformity of Cell Size      698 non-null    int64 
 3   Uniformity of Cell Shape     698 non-null    int64 
 4   Marginal Adhesion            698 non-null    int64 
 5   Single Epithelial Cell Size  698 non-null    int64 
 6   Bare Nuclei                  698 non-null    object
 7   Bland Chromatin              698 non-null    int64 
 8   Normal Nucleoli              698 non-null    int64 
 9   Mitoses                      698 non-null    int64 
 10  Class:                       698 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.1+ KB


In [15]:
df.iloc[22,:]

Sample code number             1057013
Clump Thickness                      8
Uniformity of Cell Size              4
Uniformity of Cell Shape             5
Marginal Adhesion                    1
Single Epithelial Cell Size          2
Bare Nuclei                          ?
Bland Chromatin                      7
Normal Nucleoli                      3
Mitoses                              1
Class:                               4
Name: 22, dtype: object

In [21]:
df['Bare Nuclei'] = pd.to_numeric(df['Bare Nuclei'],errors='coerce')

In [22]:
df.isnull().sum()

Sample code number              0
Clump Thickness                 0
Uniformity of Cell Size         0
Uniformity of Cell Shape        0
Marginal Adhesion               0
Single Epithelial Cell Size     0
Bare Nuclei                    16
Bland Chromatin                 0
Normal Nucleoli                 0
Mitoses                         0
Class:                          0
dtype: int64

In [24]:
df.fillna(df['Bare Nuclei'].mean(),axis=1,inplace=True)

In [26]:
df.isnull().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class:                         0
dtype: int64

In [25]:
df.iloc[22,:]

Sample code number             1.057013e+06
Clump Thickness                8.000000e+00
Uniformity of Cell Size        4.000000e+00
Uniformity of Cell Shape       5.000000e+00
Marginal Adhesion              1.000000e+00
Single Epithelial Cell Size    2.000000e+00
Bare Nuclei                    3.548387e+00
Bland Chromatin                7.000000e+00
Normal Nucleoli                3.000000e+00
Mitoses                        1.000000e+00
Class:                         4.000000e+00
Name: 22, dtype: float64

In [33]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [34]:
x

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1002945                5                        4   
1               1015425                3                        1   
2               1016277                6                        8   
3               1017023                4                        1   
4               1017122                8                       10   
..                  ...              ...                      ...   
693              776715                3                        1   
694              841769                2                        1   
695              888820                5                       10   
696              897471                4                        8   
697              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           4                  5                            7   
1                           1                  1                            2   
2                           8                  1                            3   
3                           1                  3                            2   
4                          10                  8                            7   
..                        ...                ...                          ...   
693                         1                  1                            3   
694                         1                  1                            2   
695                        10                  3                            7   
696                         6                  4                            3   
697                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  
0           10.0                3                2        1  
1            2.0                3                1        1  
2            4.0                3                7        1  
3            1.0                3                1        1  
4           10.0                9                7        1  
..           ...              ...              ...      ...  
693          2.0                1                1        1  
694          1.0                1                1        1  
695          3.0                8               10        2  
696          4.0               10                6        1  
697          5.0               10                4        1  

[698 rows x 10 columns]

In [35]:
y

0      2
1      2
2      2
3      2
4      4
      ..
693    2
694    2
695    4
696    4
697    4
Name: Class:, Length: 698, dtype: int64

### Split the dataset into training and testing dataset with test_size 25%

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

### Apply Decision Tree Classification and predict the class for the test data.

In [40]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

In [44]:
dt=DecisionTreeClassifier(criterion='gini')

In [45]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [48]:
print("traning accuracy",dt.score(x_train,y_train))
print("testing accuracy",dt.score(x_test,y_test))

traning accuracy 1.0
testing accuracy 0.92


In [49]:
y_pred=dt.predict(x_test)

In [50]:
y_pred

array([2, 2, 2, 4, 2, 4, 2, 4, 2, 2, 4, 4, 2, 4, 4, 2, 4, 4, 2, 4, 2, 4,
       4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 2,
       4, 4, 4, 2, 2, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 4,
       4, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 4, 2, 4, 2, 4, 4, 2, 4, 2, 4, 4,
       2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 4, 4, 2, 4, 2, 2, 2, 2, 4, 4, 2,
       2, 4, 4, 4, 4, 2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 4, 4,
       2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 4, 2, 2,
       2, 4, 2, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2],
      dtype=int64)

In [51]:
res=pd.DataFrame({"y_test":y_test,'y_pred':y_pred})

In [52]:
res.sample(10)

y_test  y_pred
382       2       2
666       2       2
252       4       2
685       2       2
370       2       2
447       2       2
135       2       2
291       4       4
472       2       2
19        4       4

In [54]:
cm_df=res.groupby(["y_test",'y_pred'])['y_pred'].count()

In [55]:
cm_df

y_test  y_pred
2       2         98
        4          6
4       2          8
        4         63
Name: y_pred, dtype: int64

In [63]:
from sklearn.metrics import confusion_matrix, classification_report

In [64]:
cm=confusion_matrix(y_test,y_pred)

In [65]:
print(cm)

[[98  6]
 [ 8 63]]


In [66]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           2       0.92      0.94      0.93       104
           4       0.91      0.89      0.90        71

    accuracy                           0.92       175
   macro avg       0.92      0.91      0.92       175
weighted avg       0.92      0.92      0.92       175



### Applying parameter tunning 

In [67]:
from sklearn.model_selection import cross_val_score

In [68]:
max_depth=[2,3,4,5,6,7,8,9]

In [69]:
for i in max_depth:
    score=cross_val_score(DecisionTreeClassifier(max_depth=i),x,y)
    print(f' at max depth {i}, accuracy mean is{score.mean()}')

 at max depth 2, accuracy mean is0.9298869475847894
 at max depth 3, accuracy mean is0.9270503597122302
 at max depth 4, accuracy mean is0.9312435765673175
 at max depth 5, accuracy mean is0.9169681397738951
 at max depth 6, accuracy mean is0.9341418293936281
 at max depth 7, accuracy mean is0.9212538540596095
 at max depth 8, accuracy mean is0.9255601233299074
 at max depth 9, accuracy mean is0.9255395683453237


## CV for mss

In [79]:
mss=[2,3,4,5,6,7,8,9,11,12]
for i in mss:
    score=cross_val_score(DecisionTreeClassifier(min_samples_split=i),x,y)
    print(f' min_sample_split is {i}, accuracy mean is {score.mean()}')

 min_sample_split is 2, accuracy mean is 0.919825282631038
 min_sample_split is 3, accuracy mean is 0.9241212744090443
 min_sample_split is 4, accuracy mean is 0.9255498458376156
 min_sample_split is 5, accuracy mean is 0.9212641315519013
 min_sample_split is 6, accuracy mean is 0.919825282631038
 min_sample_split is 7, accuracy mean is 0.9084069886947586
 min_sample_split is 8, accuracy mean is 0.914141829393628
 min_sample_split is 9, accuracy mean is 0.9127029804727644
 min_sample_split is 11, accuracy mean is 0.9112538540596095
 min_sample_split is 12, accuracy mean is 0.9112538540596095


### CV for criterion

In [81]:
c=["gini","entropy"]
for i in c:
    score=cross_val_score(DecisionTreeClassifier(criterion=i),x,y)
    print(f' criterion is {i}, accuracy mean is {score.mean()}')

 criterion is gini, accuracy mean is 0.9169475847893114
 criterion is entropy, accuracy mean is 0.9326927029804729


In [82]:
dt1=DecisionTreeClassifier(criterion='entropy',max_depth=6,min_samples_split=3)

In [83]:
dt1.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6, min_samples_split=3)

In [84]:
print("traning accuracy",dt1.score(x_train,y_train))
print("testing accuracy",dt1.score(x_test,y_test))

traning accuracy 0.9904397705544933
testing accuracy 0.9542857142857143


In [121]:
dt1_pred=dt1.predict(x_test)

In [122]:
dt1_pred

array([4, 4, 4, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4, 4, 4, 2, 2, 2, 2, 4, 2, 2,
       2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 2, 4, 4, 2, 2, 4, 4, 4, 2, 2, 2, 4, 2, 4, 2, 4, 2, 2, 4,
       4, 2, 2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4,
       2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4,
       2, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 4, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4,
       4, 4, 4, 4, 2, 4, 2, 4, 2, 4, 2, 2, 2, 2, 4, 2, 4, 2, 2, 4, 4],
      dtype=int64)

In [123]:
dt1_pred[:10]

array([4, 4, 4, 2, 4, 4, 2, 4, 2, 2], dtype=int64)

In [91]:
cm_df1=res.groupby(["y_test",'y_pred'])['y_pred'].count()

In [92]:
cm_df1

y_test  y_pred
2       2         98
        4          6
4       2          8
        4         63
Name: y_pred, dtype: int64

### Random Forest Classification and predict the class for the test data.

In [93]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [94]:
x

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1002945                5                        4   
1               1015425                3                        1   
2               1016277                6                        8   
3               1017023                4                        1   
4               1017122                8                       10   
..                  ...              ...                      ...   
693              776715                3                        1   
694              841769                2                        1   
695              888820                5                       10   
696              897471                4                        8   
697              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           4                  5                            7   
1                           1                  1                            2   
2                           8                  1                            3   
3                           1                  3                            2   
4                          10                  8                            7   
..                        ...                ...                          ...   
693                         1                  1                            3   
694                         1                  1                            2   
695                        10                  3                            7   
696                         6                  4                            3   
697                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  
0           10.0                3                2        1  
1            2.0                3                1        1  
2            4.0                3                7        1  
3            1.0                3                1        1  
4           10.0                9                7        1  
..           ...              ...              ...      ...  
693          2.0                1                1        1  
694          1.0                1                1        1  
695          3.0                8               10        2  
696          4.0               10                6        1  
697          5.0               10                4        1  

[698 rows x 10 columns]

In [95]:
y

0      2
1      2
2      2
3      2
4      4
      ..
693    2
694    2
695    4
696    4
697    4
Name: Class:, Length: 698, dtype: int64

In [98]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

In [99]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(523, 10)
(523,)
(175, 10)
(175,)


In [110]:
from sklearn.ensemble import RandomForestClassifier
rf1=RandomForestClassifier(criterion='entropy',max_depth=6,min_samples_split=3,n_estimators=40)

In [111]:
rf1.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=6, min_samples_split=3,
                       n_estimators=40)

In [113]:
rf1.score(x_train,y_train)

0.9866156787762906

In [114]:
rf1_pred=rf1.predict(x_test)

In [119]:
rf1_pred[:10]

array([4, 4, 4, 2, 4, 4, 2, 4, 2, 2], dtype=int64)

In [124]:
dt1_pred[:10]

array([4, 4, 4, 2, 4, 4, 2, 4, 2, 2], dtype=int64)

In [125]:
print(confusion_matrix(y_test,rf1_pred))

[[107   4]
 [  2  62]]


In [126]:
print(classification_report(y_test,rf1_pred))

              precision    recall  f1-score   support

           2       0.98      0.96      0.97       111
           4       0.94      0.97      0.95        64

    accuracy                           0.97       175
   macro avg       0.96      0.97      0.96       175
weighted avg       0.97      0.97      0.97       175

